### ISSUE TITLE
Bug: Unable to Install htdemucs_6s model

### ISSUE THREAD

**Issue by aa830** [CarlGao4/Demucs-Gui#44]
### happen

Tried installing the htdemucs_6s model from the menu, but it says "Failed to load model. Check log for more information" Log tells me a python error SSL CERTIFICATE_VERIFY_FAILED has occured.

### What is the platform you are using?

macOS

### log

```true
2024-01-20 18:05:59,985 (GuiMain.py) (Line 1412) [INFO] : Python version: 3.11.5 (main, Sep 11 2023, 08:35:00) [Clang 14.0.6 ]
2024-01-20 18:05:59,985 (GuiMain.py) (Line 1413) [INFO] : Demucs GUI version: 1.1a2
2024-01-20 18:05:59,998 (GuiMain.py) (Line 1414) [INFO] : System: macOS-14.2-arm64-arm-64bit
2024-01-20 18:06:00,002 (GuiMain.py) (Line 1415) [INFO] : Architecture: 64bit
2024-01-20 18:06:00,004 (GuiMain.py) (Line 1416) [INFO] : CPU: arm
2024-01-20 18:06:00,005 (GuiMain.py) (Line 1417) [INFO] : CPU count: 10
2024-01-20 18:06:00,005 (GuiMain.py) (Line 1418) [INFO] : System memory: 17179869184 (16GB)
2024-01-20 18:06:00,005 (GuiMain.py) (Line 1421) [INFO] : System free memory: 547291136 (521.938MB)
2024-01-20 18:06:00,005 (GuiMain.py) (Line 1424) [INFO] : System swap memory: 2147483648 (2GB)
2024-01-20 18:06:00,006 (GuiMain.py) (Line 1435) [INFO] : Using PySide6
2024-01-20 18:06:00,006 (GuiMain.py) (Line 1436) [INFO] : Qt version: 6.6.1
2024-01-20 18:06:00,006 (GuiMain.py) (Line 1437) [INFO] : PySide6 version: 6.6.1
2024-01-20 18:06:00,118 (shared.py) (Line 243) [INFO] : [1] Thread starter (separator.py) starts
2024-01-20 18:06:00,132 (GuiMain.py) (Line 1442) [DEBUG] : Supported styles: macOS, Windows, Fusion
2024-01-20 18:06:00,133 (GuiMain.py) (Line 1446) [DEBUG] : Current style: macos
2024-01-20 18:06:00,911 (separator.py) (Line 54) [INFO] : Intel Extension for PyTorch is not installed
2024-01-20 18:06:01,001 (audio.py) (Line 34) [INFO] : Soundfile version: 0.12.1
2024-01-20 18:06:01,002 (audio.py) (Line 35) [INFO] : libsndfile version: 1.2.0
2024-01-20 18:06:01,002 (audio.py) (Line 36) [INFO] : SoXR version: 0.3.7
2024-01-20 18:06:01,003 (audio.py) (Line 37) [INFO] : libsoxr version: 0.1.3-7-gacc0dac
2024-01-20 18:06:01,003 (separator.py) (Line 62) [INFO] : Demucs version: 4.1.0a2
2024-01-20 18:06:01,004 (separator.py) (Line 63) [INFO] : PyTorch version: 2.0.1
2024-01-20 18:06:02,092 (audio.py) (Line 49) [INFO] : ffmpeg -version output:
ffmpeg version n6.0-tessus Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/lib --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-libcaca --enable-version3 --disable-ffplay --enable-ffmpeg --enable-ffprobe
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

2024-01-20 18:06:02,120 (audio.py) (Line 54) [INFO] : Using ffmpeg from /Applications/Demucs-GUI.app/Contents/Frameworks/ffmpeg/ffmpeg
2024-01-20 18:06:02,120 (audio.py) (Line 55) [INFO] : ffprobe -version output:
ffprobe version n6.0-tessus Copyright (c) 2007-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/lib --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-libcaca --enable-version3 --disable-ffplay --enable-ffmpeg --enable-ffprobe
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

2024-01-20 18:06:03,126 (shared.py) (Line 254) [INFO] : [1] Thread starter (separator.py) ends
2024-01-20 18:06:03,148 (shared.py) (Line 243) [INFO] : [2] Thread checkUpdate (shared.py) starts
2024-01-20 18:06:03,157 (shared.py) (Line 270) [INFO] : Checking for updates...
2024-01-20 18:06:04,390 (shared.py) (Line 276) [WARNING] : Failed to check for updates:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shared.py", line 271, in checkUpdate
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:06:04,405 (shared.py) (Line 254) [INFO] : [2] Thread checkUpdate (shared.py) ends
2024-01-20 18:06:08,226 (shared.py) (Line 243) [INFO] : [3] Thread loadModel (GuiMain.py) starts
2024-01-20 18:06:08,238 (GuiMain.py) (Line 505) [INFO] : Loading model htdemucs_6s from repo "remote"
2024-01-20 18:06:08,239 (separator.py) (Line 259) [INFO] : Downloading model 5c90dfd2 from https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th
2024-01-20 18:06:08,533 (GuiMain.py) (Line 293) [ERROR] : Failed to load model htdemucs_6s from remote repo:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GuiMain.py", line 291, in loadModel
  File "separator.py", line 227, in __init__
  File "separator.py", line 248, in ensureDownloaded
  File "separator.py", line 262, in ensureDownloaded
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:06:08,613 (shared.py) (Line 254) [INFO] : [3] Thread loadModel (GuiMain.py) ends
2024-01-20 18:09:08,788 (shared.py) (Line 243) [INFO] : [4] Thread loadModel (GuiMain.py) starts
2024-01-20 18:09:08,797 (GuiMain.py) (Line 505) [INFO] : Loading model htdemucs_6s from repo "remote"
2024-01-20 18:09:08,798 (separator.py) (Line 259) [INFO] : Downloading model 5c90dfd2 from https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th
2024-01-20 18:09:08,932 (GuiMain.py) (Line 293) [ERROR] : Failed to load model htdemucs_6s from remote repo:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GuiMain.py", line 291, in loadModel
  File "separator.py", line 227, in __init__
  File "separator.py", line 248, in ensureDownloaded
  File "separator.py", line 262, in ensureDownloaded
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:09:09,000 (shared.py) (Line 254) [INFO] : [4] Thread loadModel (GuiMain.py) ends
2024-01-20 18:09:24,654 (shared.py) (Line 243) [INFO] : [5] Thread loadModel (GuiMain.py) starts
2024-01-20 18:09:24,661 (GuiMain.py) (Line 505) [INFO] : Loading model htdemucs_6s from repo "remote"
2024-01-20 18:09:24,661 (separator.py) (Line 259) [INFO] : Downloading model 5c90dfd2 from https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th
2024-01-20 18:09:24,781 (GuiMain.py) (Line 293) [ERROR] : Failed to load model htdemucs_6s from remote repo:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GuiMain.py", line 291, in loadModel
  File "separator.py", line 227, in __init__
  File "separator.py", line 248, in ensureDownloaded
  File "separator.py", line 262, in ensureDownloaded
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:09:24,845 (shared.py) (Line 254) [INFO] : [5] Thread loadModel (GuiMain.py) ends
2024-01-20 18:09:37,270 (shared.py) (Line 243) [INFO] : [6] Thread loadModel (GuiMain.py) starts
2024-01-20 18:09:37,277 (GuiMain.py) (Line 505) [INFO] : Loading model htdemucs_6s from repo "remote"
2024-01-20 18:09:37,278 (separator.py) (Line 259) [INFO] : Downloading model 5c90dfd2 from https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th
2024-01-20 18:09:37,307 (GuiMain.py) (Line 293) [ERROR] : Failed to load model htdemucs_6s from remote repo:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GuiMain.py", line 291, in loadModel
  File "separator.py", line 227, in __init__
  File "separator.py", line 248, in ensureDownloaded
  File "separator.py", line 262, in ensureDownloaded
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:09:37,358 (shared.py) (Line 254) [INFO] : [6] Thread loadModel (GuiMain.py) ends
2024-01-20 18:12:04,778 (shared.py) (Line 243) [INFO] : [7] Thread checkUpdate (shared.py) starts
2024-01-20 18:12:04,782 (shared.py) (Line 270) [INFO] : Checking for updates...
2024-01-20 18:12:04,869 (shared.py) (Line 276) [WARNING] : Failed to check for updates:
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1286, in request
  File "http/client.py", line 1332, in _send_request
  File "http/client.py", line 1281, in endheaders
  File "http/client.py", line 1041, in _send_output
  File "http/client.py", line 979, in send
  File "http/client.py", line 1458, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shared.py", line 271, in checkUpdate
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

2024-01-20 18:12:07,000 (shared.py) (Line 254) [INFO] : [7] Thread checkUpdate (shared.py) ends
```

**Comment by VinneyUK** [comment]
I'm getting the same error ! :(

**Comment by CarlGao4** [comment]
Found solution. May be fixed in 1.1b1

**Comment by VinneyUK** [comment]
> Found solution. May be fixed in 1.1b1

ETA??

**Comment by CarlGao4** [comment]
Sorry but I was on vacation for the past month so I had no computer to finish it. I'll continue developing as soon as possible

**Comment by VinneyUK** [comment]
> Sorry but I was on vacation for the past month so I had no computer to finish it. I'll continue developing as soon as possible

any updates please :)

**Comment by CarlGao4** [comment]
Developing presets (saving output stem settings)
I decided that this should be released along with 1.1b1

**Comment by CarlGao4** [comment]
1.1b1 Released, but my macOS VM went something wrong and can't be started, reinstalling...

**Comment by VinneyUK** [comment]
thank you for fixing this - however I can't see the macOS files, only windows?

**Comment by aa830** [comment]
Funny, I dont see any new release?

**Comment by aa830** [comment]
Where is the mac release?

**Comment by CarlGao4** [comment]
> I can't see the macOS files, only windows?

Yeah... I'm still restoring my environment to pack it...

> Funny, I dont see any new release?

It is a beta release, so it won't show on the main page, but you can see it on the [release page](https://github.com/CarlGao4/Demucs-Gui/releases)

**Comment by CarlGao4** [comment]
Now x86_64 has been uploaded

**Comment by CarlGao4** [comment]
> Ps. I made a donation to you. :) Ant Vincent.
Thanks for your support!

**Comment by CarlGao4** [comment]
@VinneyUK @aa830 Please try whether this release fixed the issue

**Comment by VinneyUK** [comment]
Hi @CarlGao4 thank you. Model loading fine now, however separation is broken and hangs on stem write :(

<img width="595" alt="Screenshot 2024-03-14 at 19 47 49" src="https://github.com/CarlGao4/Demucs-Gui/assets/66467679/80a1c81f-69e3-4ea5-8003-f2199e1fabf3">

`
2024-03-14 19:41:28,716 (shared.py) (Line 300) [INFO] : [3] Thread loadModel (GuiMain.py) ends
2024-03-14 19:41:28,720 (separator.py) (Line 125) [INFO] : MPS backend is available
2024-03-14 19:41:28,725 (GuiMain.py) (Line 1234) [INFO] : Preset stem key: ["bass","drums","other","vocals"]
2024-03-14 19:41:28,725 (GuiMain.py) (Line 1386) [INFO] : Adding saved presets: []
2024-03-14 19:41:38,786 (shared.py) (Line 289) [INFO] : [4] Thread separate (separator.py) starts
2024-03-14 19:41:38,787 (separator.py) (Line 446) [INFO] : Start separating audio: 02-ruff_driverz_pres_arrola-dreaming__original_mix-l4l.flac
2024-03-14 19:41:38,787 (separator.py) (Line 447) [INFO] : Parameters: segment=7.80 overlap=0.25 shifts=0
2024-03-14 19:41:38,788 (separator.py) (Line 448) [INFO] : Device: mps
2024-03-14 19:41:38,789 (audio.py) (Line 66) [DEBUG] : Reading audio with soundfile: /Users/Vinney/Desktop/02-ruff_driverz_pres_arrola-dreaming__original_mix-l4l.flac
2024-03-14 19:41:39,239 (audio.py) (Line 82) [INFO] : Read audio /Users/Vinney/Desktop/02-ruff_driverz_pres_arrola-dreaming__original_mix-l4l.flac: samplerate=44100 shape=(19235180, 2)
2024-03-14 19:41:39,283 (separator.py) (Line 478) [INFO] : Running separation...
2024-03-14 19:42:59,909 (shared.py) (Line 205) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 2
2024-03-14 19:43:00,391 (shared.py) (Line 205) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 0
2024-03-14 19:45:33,754 (separator.py) (Line 503) [INFO] : Saving separated audio...
2024-03-14 19:45:33,755 (shared.py) (Line 289) [INFO] : [5] Thread save (GuiMain.py) starts
2024-03-14 19:45:33,766 (shared.py) (Line 300) [INFO] : [4] Thread separate (separator.py) ends
2024-03-14 19:45:33,771 (GuiMain.py) (Line 1506) [INFO] : Mixing stem drums
2024-03-14 19:45:34,155 (shared.py) (Line 295) [ERROR] : [5] Thread save (GuiMain.py) failed:
Traceback (most recent call last):
  File "shared.py", line 293, in run_and_log
  File "GuiMain.py", line 953, in save
TypeError: AddHistory() missing 1 required keyword-only argument: 'value'

2024-03-14 19:45:34,162 (shared.py) (Line 300) [INFO] : [5] Thread save (GuiMain.py) ends

`

**Comment by CarlGao4** [comment]
Release file updated. Please try again.

**Comment by CarlGao4** [comment]
@VinneyUK Please close this if 1.1 has fixed it
