### ISSUE TITLE
Bug: 1.1b1 can't save files

### ISSUE THREAD

**Issue by KoSChicken** [CarlGao4/Demucs-Gui#48]
### happen

1. Select a file and start separation.
2. Status bar stuck in 100% and no stem files saved.

### What is the platform you are using?

Windows

### log

```true
Model 0:
　Type: HTDemucs
　Default segment: 7.8
　Weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2024-03-13 14:43:32,456 (shared.py) (Line 300) [INFO] : [3] Thread loadModel (GuiMain.py) ends
2024-03-13 14:43:32,489 (GuiMain.py) (Line 1234) [INFO] : Preset stem key: ["bass","drums","guitar","other","piano","vocals"]
2024-03-13 14:43:32,489 (GuiMain.py) (Line 1386) [INFO] : Adding saved presets: []
2024-03-13 14:44:10,631 (shared.py) (Line 289) [INFO] : [4] Thread separate (separator.py) starts
2024-03-13 14:44:10,631 (separator.py) (Line 446) [INFO] : Start separating audio: Audio.mp3
2024-03-13 14:44:10,631 (separator.py) (Line 447) [INFO] : Parameters: segment=7.80 overlap=0.25 shifts=10
2024-03-13 14:44:10,631 (separator.py) (Line 448) [INFO] : Device: cuda:0
2024-03-13 14:44:10,632 (audio.py) (Line 66) [DEBUG] : Reading audio with soundfile: D:\Audio.mp3
2024-03-13 14:44:10,909 (audio.py) (Line 82) [INFO] : Read audio D:\Audio.mp3: samplerate=44100 shape=(10137647, 2)
2024-03-13 14:44:10,922 (separator.py) (Line 478) [INFO] : Running separation...
2024-03-13 14:45:03,024 (separator.py) (Line 503) [INFO] : Saving separated audio...
2024-03-13 14:45:03,026 (shared.py) (Line 289) [INFO] : [5] Thread save (GuiMain.py) starts
2024-03-13 14:45:03,029 (shared.py) (Line 300) [INFO] : [4] Thread separate (separator.py) ends
2024-03-13 14:45:03,030 (shared.py) (Line 295) [ERROR] : [5] Thread save (GuiMain.py) failed:
Traceback (most recent call last):
  File "shared.py", line 293, in run_and_log
  File "GuiMain.py", line 943, in save
AttributeError: 'Mixer' object has no attribute 'setEnable'

2024-03-13 14:45:03,030 (shared.py) (Line 300) [INFO] : [5] Thread save (GuiMain.py) ends
```

**Comment by CarlGao4** [comment]
Just a mistake...

**Comment by KoSChicken** [comment]
> Just a mistake...

😂

**Comment by CarlGao4** [comment]
Please try 1.1b2

**Comment by KoSChicken** [comment]
> Please try 1.1b2

Fixed.
