### ISSUE TITLE
All models stuck on 100%

### ISSUE THREAD

**Issue by ertup0** [CarlGao4/Demucs-Gui#49]
No stems are generating and ETA is 23:59:59
GPU: RTX 2060S
OS: Windows 10

log

2024-03-13 19:05:09,553 (GuiMain.py) (Line 1729) [INFO] : Python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
2024-03-13 19:05:09,553 (GuiMain.py) (Line 1730) [INFO] : Demucs GUI version: 1.1b1
2024-03-13 19:05:09,606 (GuiMain.py) (Line 1731) [INFO] : System: Windows-10-10.0.19044-SP0
2024-03-13 19:05:09,606 (GuiMain.py) (Line 1732) [INFO] : Architecture: 64bit
2024-03-13 19:05:09,606 (GuiMain.py) (Line 1733) [INFO] : CPU: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
2024-03-13 19:05:09,606 (GuiMain.py) (Line 1734) [INFO] : CPU count: 8
2024-03-13 19:05:09,612 (GuiMain.py) (Line 1735) [INFO] : System memory: 17121316864 (15.945GB)
2024-03-13 19:05:09,617 (GuiMain.py) (Line 1738) [INFO] : System free memory: 6597869568 (6.145GB)
2024-03-13 19:05:10,029 (GuiMain.py) (Line 1741) [INFO] : System swap memory: 12786352128 (11.908GB)
2024-03-13 19:05:10,175 (find_device_win.py) (Line 111) [INFO] : Found GPU: NVIDIA GeForce RTX 2060 SUPER (10DE:1F06)
2024-03-13 19:05:10,176 (GuiMain.py) (Line 1755) [INFO] : Using PySide6
2024-03-13 19:05:10,176 (GuiMain.py) (Line 1756) [INFO] : Qt version: 6.5.3
2024-03-13 19:05:10,176 (GuiMain.py) (Line 1757) [INFO] : PySide6 version: 6.5.3
2024-03-13 19:05:10,228 (shared.py) (Line 289) [INFO] : [1] Thread starter (separator.py) starts
2024-03-13 19:05:10,304 (GuiMain.py) (Line 1762) [DEBUG] : Supported styles: windowsvista, Windows, Fusion
2024-03-13 19:05:10,306 (GuiMain.py) (Line 1766) [DEBUG] : Current style: windowsvista
2024-03-13 19:05:12,475 (separator.py) (Line 64) [INFO] : Intel Extension for PyTorch is not installed
2024-03-13 19:05:12,635 (audio.py) (Line 34) [INFO] : Soundfile version: 0.12.1
2024-03-13 19:05:12,635 (audio.py) (Line 35) [INFO] : libsndfile version: 1.2.0
2024-03-13 19:05:12,635 (audio.py) (Line 36) [INFO] : SoXR version: 0.3.7
2024-03-13 19:05:12,635 (audio.py) (Line 37) [INFO] : libsoxr version: 0.1.3-7-gacc0dac
2024-03-13 19:05:12,635 (separator.py) (Line 85) [INFO] : Demucs version: 4.1.0a2
2024-03-13 19:05:12,636 (separator.py) (Line 86) [INFO] : PyTorch version: 2.0.1+cu118
2024-03-13 19:05:12,637 (separator.py) (Line 95) [INFO] : CUDA Info: _CudaDeviceProperties(name='NVIDIA GeForce RTX 2060 SUPER', major=7, minor=5, total_memory=8191MB, multi_processor_count=34)
2024-03-13 19:05:13,684 (audio.py) (Line 49) [INFO] : ffmpeg -version output:
ffmpeg version 6.1.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers

built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

libavutil      58. 29.100 / 58. 29.100

libavcodec     60. 31.102 / 60. 31.102

libavformat    60. 16.100 / 60. 16.100

libavdevice    60.  3.100 / 60.  3.100

libavfilter     9. 12.100 /  9. 12.100

libswscale      7.  5.100 /  7.  5.100

libswresample   4. 12.100 /  4. 12.100

libpostproc    57.  3.100 / 57.  3.100

2024-03-13 19:05:13,732 (audio.py) (Line 54) [INFO] : Using ffmpeg from D:\dwnl\web_dwhl\chrome_dwhl\Demucs-GUI_1.1b1_cuda\ffmpeg\ffmpeg.EXE
2024-03-13 19:05:13,733 (audio.py) (Line 55) [INFO] : ffprobe -version output:
ffprobe version 6.1.1-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers

built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

libavutil      58. 29.100 / 58. 29.100

libavcodec     60. 31.102 / 60. 31.102

libavformat    60. 16.100 / 60. 16.100

libavdevice    60.  3.100 / 60.  3.100

libavfilter     9. 12.100 /  9. 12.100

libswscale      7.  5.100 /  7.  5.100

libswresample   4. 12.100 /  4. 12.100

libpostproc    57.  3.100 / 57.  3.100

2024-03-13 19:05:14,734 (shared.py) (Line 300) [INFO] : [1] Thread starter (separator.py) ends
2024-03-13 19:05:14,740 (shared.py) (Line 289) [INFO] : [2] Thread checkUpdate (shared.py) starts
2024-03-13 19:05:14,751 (shared.py) (Line 316) [INFO] : Checking for updates...
2024-03-13 19:05:16,098 (shared.py) (Line 319) [INFO] : Latest version: 1.1b1
2024-03-13 19:05:16,099 (shared.py) (Line 300) [INFO] : [2] Thread checkUpdate (shared.py) ends
2024-03-13 19:05:19,300 (shared.py) (Line 289) [INFO] : [3] Thread loadModel (GuiMain.py) starts
2024-03-13 19:05:19,303 (GuiMain.py) (Line 625) [INFO] : Loading model htdemucs from repo D:\dwnl\web_dwhl\chrome_dwhl\Demucs-GUI_1.1b1_cuda\pretrained
2024-03-13 19:05:20,254 (GuiMain.py) (Line 653) [INFO] : Model loaded within 0.9470s
2024-03-13 19:05:20,255 (GuiMain.py) (Line 654) [INFO] : Model: htdemucs
Repo: D:\dwnl\web_dwhl\chrome_dwhl\Demucs-GUI_1.1b1_cuda\pretrained
Type: Bag of models
Audio channels: 2
Sample rate: 44100
Sources: drums, bass, other, vocals

Model 0:
　Type: HTDemucs
　Default segment: 7.8
　Weight: [1.0, 1.0, 1.0, 1.0]
2024-03-13 19:05:20,255 (shared.py) (Line 300) [INFO] : [3] Thread loadModel (GuiMain.py) ends
2024-03-13 19:05:20,266 (GuiMain.py) (Line 1234) [INFO] : Preset stem key: ["bass","drums","other","vocals"]
2024-03-13 19:05:20,266 (GuiMain.py) (Line 1386) [INFO] : Adding saved presets: []
2024-03-13 19:05:33,313 (shared.py) (Line 289) [INFO] : [4] Thread separate (separator.py) starts
2024-03-13 19:05:33,314 (separator.py) (Line 446) [INFO] : Start separating audio: pb_theme_pc_speaker.mp3
2024-03-13 19:05:33,314 (separator.py) (Line 447) [INFO] : Parameters: segment=7.80 overlap=0.25 shifts=0
2024-03-13 19:05:33,314 (separator.py) (Line 448) [INFO] : Device: cuda:0
2024-03-13 19:05:33,316 (audio.py) (Line 66) [DEBUG] : Reading audio with soundfile: D:\dwnl\web_dwhl\chrome_dwhl\drive-download-20230630T212355Z-001\Progressbar95\steamapps\common\Progressbar95\Resources\sound\pb_theme_pc_speaker.mp3
2024-03-13 19:05:33,375 (audio.py) (Line 82) [INFO] : Read audio D:\dwnl\web_dwhl\chrome_dwhl\drive-download-20230630T212355Z-001\Progressbar95\steamapps\common\Progressbar95\Resources\sound\pb_theme_pc_speaker.mp3: samplerate=44100 shape=(2540160, 1)
2024-03-13 19:05:33,377 (separator.py) (Line 478) [INFO] : Running separation...
2024-03-13 19:05:39,761 (separator.py) (Line 503) [INFO] : Saving separated audio...
2024-03-13 19:05:39,762 (shared.py) (Line 289) [INFO] : [5] Thread save (GuiMain.py) starts
2024-03-13 19:05:39,764 (shared.py) (Line 295) [ERROR] : [5] Thread save (GuiMain.py) failed:
Traceback (most recent call last):
  File "shared.py", line 293, in run_and_log
  File "GuiMain.py", line 943, in save
AttributeError: 'Mixer' object has no attribute 'setEnable'

2024-03-13 19:05:39,764 (shared.py) (Line 300) [INFO] : [5] Thread save (GuiMain.py) ends
2024-03-13 19:05:39,774 (shared.py) (Line 300) [INFO] : [4] Thread separate (separator.py) ends
2024-03-13 19:05:47,239 (shared.py) (Line 205) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 2
2024-03-13 19:05:48,806 (shared.py) (Line 205) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 0

**Comment by CarlGao4** [comment]
Duplicate #48
