### ISSUE TITLE
ETA indicator broken

### ISSUE THREAD

**Issue by Coderr123** [CarlGao4/Demucs-Gui#70]
### happen

The ETA indicator usually starts at 23 hours and never progresses much even when the separation takes only a few minutes.

### What is the platform you are using?

macOS

### log

```true
2024-05-21 18:23:42,161 (GuiMain.py) (Line 2049) [INFO] : Python version: 3.11.9 (main, Apr 19 2024, 11:49:16) [Clang 14.0.6 ]
2024-05-21 18:23:42,162 (GuiMain.py) (Line 2050) [INFO] : Demucs GUI version: 1.2
2024-05-21 18:23:42,177 (GuiMain.py) (Line 2051) [INFO] : System: macOS-14.1.1-arm64-arm-64bit
2024-05-21 18:23:42,181 (GuiMain.py) (Line 2052) [INFO] : Architecture: 64bit
2024-05-21 18:23:42,181 (GuiMain.py) (Line 2053) [INFO] : CPU: arm
2024-05-21 18:23:42,182 (GuiMain.py) (Line 2054) [INFO] : CPU count: 8
2024-05-21 18:23:42,182 (GuiMain.py) (Line 2055) [INFO] : System memory: 8589934592 (8GB)
2024-05-21 18:23:42,182 (GuiMain.py) (Line 2058) [INFO] : System free memory: 60260352 (57.469MB)
2024-05-21 18:23:42,182 (GuiMain.py) (Line 2062) [INFO] : System swap memory: 2147483648 (2GB)
2024-05-21 18:23:42,183 (GuiMain.py) (Line 2080) [INFO] : Using PySide6
2024-05-21 18:23:42,183 (GuiMain.py) (Line 2081) [INFO] : Qt version: 6.7.0
2024-05-21 18:23:42,183 (GuiMain.py) (Line 2082) [INFO] : PySide6 version: 6.7.0
2024-05-21 18:23:42,342 (shared.py) (Line 360) [INFO] : [1] Thread starter (separator.py) starts
2024-05-21 18:23:42,368 (GuiMain.py) (Line 2087) [DEBUG] : Supported styles: macOS, Windows, Fusion
2024-05-21 18:23:42,369 (GuiMain.py) (Line 2093) [DEBUG] : Current style: macos
2024-05-21 18:23:43,586 (separator.py) (Line 66) [INFO] : Intel Extension for PyTorch is not installed
2024-05-21 18:23:43,601 (__init__.py) (Line 68) [DEBUG] : Failed to initialize sox extension
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/Applications/Demucs-GUI.app/Contents/Frameworks/torchaudio/lib/libtorchaudio_sox.so, 0x0006): Library not loaded: @rpath/libsox.dylib
  Referenced from: <20E00ABB-13B8-31A1-A605-453D3F4E7C79> /Applications/Demucs-GUI.app/Contents/Frameworks/torchaudio/lib/libtorchaudio_sox.so
  Reason: tried: '/Applications/Demucs-GUI.app/Contents/Frameworks/torchaudio/lib/../../libsox.dylib' (no such file), '/Applications/Demucs-GUI.app/Contents/Frameworks/torchaudio/lib/../../libsox.dylib' (no such file), '/Applications/Demucs-GUI.app/Contents/Frameworks/lib-dynload/../libsox.dylib' (no such file), '/usr/local/lib/libsox.dylib' (no such file), '/usr/lib/libsox.dylib' (no such file, not in dyld cache)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "torchaudio/_extension/__init__.py", line 60, in <module>
    _init_sox()
  File "torchaudio/_extension/utils.py", line 70, in _init_sox
    _load_lib("libtorchaudio_sox")
  File "torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "PyInstaller/loader/pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '/Applications/Demucs-GUI.app/Contents/Frameworks/torchaudio/lib/libtorchaudio_sox.so'. Most likely this dynlib/dll was not found when the application was frozen.
2024-05-21 18:23:43,602 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 6.
2024-05-21 18:23:43,621 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 6 extension.
Traceback (most recent call last):
  File "torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: dlopen(libavutil.58.dylib, 0x0006): tried: 'libavutil.58.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavutil.58.dylib' (no such file), '/Applications/Demucs-GUI.app/Contents/Frameworks/torch/lib/../../libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache), 'libavutil.58.dylib' (no such file), '/usr/local/lib/libavutil.58.dylib' (no such file), '/usr/lib/libavutil.58.dylib' (no such file, not in dyld cache)
2024-05-21 18:23:43,622 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 5.
2024-05-21 18:23:43,624 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 5 extension.
Traceback (most recent call last):
  File "torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: dlopen(libavutil.57.dylib, 0x0006): tried: 'libavutil.57.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavutil.57.dylib' (no such file), '/Applications/Demucs-GUI.app/Contents/Frameworks/torch/lib/../../libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache), 'libavutil.57.dylib' (no such file), '/usr/local/lib/libavutil.57.dylib' (no such file), '/usr/lib/libavutil.57.dylib' (no such file, not in dyld cache)
2024-05-21 18:23:43,624 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 4.
2024-05-21 18:23:43,626 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 4 extension.
Traceback (most recent call last):
  File "torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: dlopen(libavutil.56.dylib, 0x0006): tried: 'libavutil.56.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibavutil.56.dylib' (no such file), '/Applications/Demucs-GUI.app/Contents/Frameworks/torch/lib/../../libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache), 'libavutil.56.dylib' (no such file), '/usr/local/lib/libavutil.56.dylib' (no such file), '/usr/lib/libavutil.56.dylib' (no such file, not in dyld cache)
2024-05-21 18:23:43,626 (__init__.py) (Line 96) [DEBUG] : Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "torchaudio/_extension/__init__.py", line 89, in <module>
    _FFMPEG_EXT = _init_ffmpeg()
                  ^^^^^^^^^^^^^^
  File "torchaudio/_extension/utils.py", line 162, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers, show_error)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "torchaudio/_extension/utils.py", line 132, in _find_ffmpeg_extension
    raise ImportError(f"Failed to intialize FFmpeg extension. Tried versions: {ffmpeg_vers}")
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4']
PyInstaller/loader/pyimod02_importers.py:419: UserWarning: TorchAudio's global backend is now deprecated. Please enable distpatcher by setting `TORCHAUDIO_USE_BACKEND_DISPATCHER=1`, and specify backend when calling load/info/save function.
2024-05-21 18:23:43,745 (audio.py) (Line 34) [INFO] : Soundfile version: 0.12.1
2024-05-21 18:23:43,746 (audio.py) (Line 35) [INFO] : libsndfile version: 1.2.0
2024-05-21 18:23:43,746 (audio.py) (Line 36) [INFO] : SoXR version: 0.3.7
2024-05-21 18:23:43,746 (audio.py) (Line 37) [INFO] : libsoxr version: 0.1.3-7-gacc0dac
2024-05-21 18:23:43,747 (separator.py) (Line 88) [INFO] : Demucs version: 4.1.0a3
2024-05-21 18:23:43,747 (separator.py) (Line 89) [INFO] : PyTorch version: 2.1.2
2024-05-21 18:23:44,887 (audio.py) (Line 49) [INFO] : ffmpeg -version output:
ffmpeg version n6.0-tessus Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/lib --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-libcaca --enable-version3 --disable-ffplay --enable-ffmpeg --enable-ffprobe
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

2024-05-21 18:23:44,910 (audio.py) (Line 54) [INFO] : Using ffmpeg from /Applications/Demucs-GUI.app/Contents/Frameworks/ffmpeg/ffmpeg
2024-05-21 18:23:44,911 (audio.py) (Line 55) [INFO] : ffprobe -version output:
ffprobe version n6.0-tessus Copyright (c) 2007-2023 the FFmpeg developers
built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/lib --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-libcaca --enable-version3 --disable-ffplay --enable-ffmpeg --enable-ffprobe
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100

2024-05-21 18:23:45,917 (shared.py) (Line 371) [INFO] : [1] Thread starter (separator.py) ends
2024-05-21 18:23:45,960 (shared.py) (Line 360) [INFO] : [2] Thread checkUpdate (shared.py) starts
2024-05-21 18:23:45,968 (shared.py) (Line 387) [INFO] : Checking for updates...
2024-05-21 18:23:46,778 (shared.py) (Line 390) [INFO] : Latest version: 1.2
2024-05-21 18:23:46,779 (shared.py) (Line 371) [INFO] : [2] Thread checkUpdate (shared.py) ends
2024-05-21 18:23:50,121 (shared.py) (Line 360) [INFO] : [3] Thread loadModel (GuiMain.py) starts
2024-05-21 18:23:50,134 (GuiMain.py) (Line 657) [INFO] : Loading model htdemucs_6s from repo "remote"
2024-05-21 18:23:50,419 (GuiMain.py) (Line 685) [INFO] : Model loaded within 0.2817s
2024-05-21 18:23:50,419 (GuiMain.py) (Line 686) [INFO] : Model: htdemucs_6s
Repo: "remote"
Type: Bag of models
Audio channels: 2
Sample rate: 44100
Sources: drums, bass, other, vocals, guitar, piano

Model 0:
　Type: HTDemucs
　Default segment: 7.8
　Weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2024-05-21 18:23:50,420 (shared.py) (Line 371) [INFO] : [3] Thread loadModel (GuiMain.py) ends
2024-05-21 18:23:50,423 (separator.py) (Line 132) [INFO] : MPS backend is available
2024-05-21 18:23:50,434 (shared.py) (Line 274) [DEBUG] : (switchEncoder) Set history ('encoder',) to 0
2024-05-21 18:23:50,434 (shared.py) (Line 276) [DEBUG] : History not changed, ignored
2024-05-21 18:23:50,436 (GuiMain.py) (Line 1512) [INFO] : Preset stem key: ["bass","drums","guitar","other","piano","vocals"]
2024-05-21 18:23:50,436 (GuiMain.py) (Line 1667) [INFO] : Adding saved presets: []
2024-05-21 18:24:47,451 (shared.py) (Line 274) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 2
2024-05-21 18:24:48,352 (shared.py) (Line 274) [DEBUG] : (<lambda>) Set history ('separate_once_added',) to 0
2024-05-21 18:24:52,151 (shared.py) (Line 274) [DEBUG] : (<lambda>) Set history ('sample_fmt',) to float32
2024-05-21 18:26:09,006 (shared.py) (Line 360) [INFO] : [4] Thread separate (separator.py) starts
2024-05-21 18:26:09,008 (separator.py) (Line 460) [INFO] : Start separating audio: Africa.Ls.wav
2024-05-21 18:26:09,008 (separator.py) (Line 461) [INFO] : Parameters: segment=7.80 overlap=0.45 shifts=20
2024-05-21 18:26:09,008 (separator.py) (Line 462) [INFO] : Device: mps
2024-05-21 18:26:09,010 (audio.py) (Line 66) [DEBUG] : Reading audio with soundfile: /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/Africa.Ls.wav
2024-05-21 18:26:09,067 (audio.py) (Line 82) [INFO] : Read audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/Africa.Ls.wav: samplerate=88200 shape=(26235040, 1)
2024-05-21 18:26:09,068 (audio.py) (Line 85) [INFO] : Samplerate 88200 doesn't match target 44100, resampling with SoXR
2024-05-21 18:26:09,273 (separator.py) (Line 498) [INFO] : Running separation...
2024-05-21 18:56:19,129 (separator.py) (Line 525) [INFO] : Saving separated audio...
2024-05-21 18:56:19,184 (shared.py) (Line 360) [INFO] : [5] Thread save (GuiMain.py) starts
2024-05-21 18:56:19,246 (shared.py) (Line 371) [INFO] : [4] Thread separate (separator.py) ends
2024-05-21 18:56:19,309 (shared.py) (Line 274) [DEBUG] : (save) Set history ('save_location',) to OrderedSet(['separated/{model}/{track}/{stem}.{ext}', 'separated/{model}/{track}/{stem}', '/separated/{model}/{track}/{stem}.{ext}', '/Users/name/Desktop/Stems'])
2024-05-21 18:56:19,343 (GuiMain.py) (Line 1812) [INFO] : Mixing stem drums
2024-05-21 18:56:20,413 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/drums.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:20,420 (GuiMain.py) (Line 1812) [INFO] : Mixing stem bass
2024-05-21 18:56:20,907 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/bass.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:20,908 (GuiMain.py) (Line 1812) [INFO] : Mixing stem other
2024-05-21 18:56:21,541 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/other.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:21,543 (GuiMain.py) (Line 1812) [INFO] : Mixing stem vocals
2024-05-21 18:56:22,127 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/vocals.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:22,130 (GuiMain.py) (Line 1812) [INFO] : Mixing stem guitar
2024-05-21 18:56:23,112 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/guitar.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:23,148 (GuiMain.py) (Line 1812) [INFO] : Mixing stem piano
2024-05-21 18:56:23,685 (audio.py) (Line 129) [INFO] : Saved audio /Users/name/Library/Mobile Documents/com~apple~CloudDocs/untitled folder icloud/Toto_IV.2003.DTS.5.1..flac/Africa (5.1 Decompiled Stems)/separated/htdemucs_6s/Africa.Ls/piano.wav: shape=torch.Size([1, 13117520])
2024-05-21 18:56:23,716 (shared.py) (Line 371) [INFO] : [5] Thread save (GuiMain.py) ends
```

**Comment by CarlGao4** [comment]
No plan to fix this. Usually the model should prepare data when separating the first segment, which will cause the first segment to take more time than the others.
