### ISSUE TITLE
Bug: 1.31a_cuda_mkl hangs on splash screen

### ISSUE THREAD

**Issue by Sinnaminty** [CarlGao4/Demucs-Gui#91]
### happen

1. Launched Demucs-Gui.exe
2. Stays stuck on "Starting..."

### What is the platform you are using?

Windows

### log

```true
2024-10-23 20:45:38,818 (GuiMain.py) (Line 2276) [INFO] : Python version: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:50:51) [MSC v.1941 64 bit (AMD64)]
2024-10-23 20:45:38,818 (GuiMain.py) (Line 2277) [INFO] : Demucs GUI version: 1.3a1
2024-10-23 20:45:38,890 (GuiMain.py) (Line 2278) [INFO] : System: Windows-10-10.0.22631-SP0
2024-10-23 20:45:38,890 (GuiMain.py) (Line 2279) [INFO] : Architecture: 64bit
2024-10-23 20:45:38,890 (GuiMain.py) (Line 2280) [INFO] : CPU: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
2024-10-23 20:45:38,891 (GuiMain.py) (Line 2281) [INFO] : CPU count: 24
2024-10-23 20:45:38,899 (GuiMain.py) (Line 2282) [INFO] : System memory: 51459039232 (47.925GB)
2024-10-23 20:45:38,906 (GuiMain.py) (Line 2285) [INFO] : System free memory: 40394526720 (37.62GB)
2024-10-23 20:45:39,164 (GuiMain.py) (Line 2289) [INFO] : System swap memory: 3221225472 (3GB)
2024-10-23 20:45:39,439 (find_device_win.py) (Line 344) [INFO] : Found GPU: NVIDIA GeForce RTX 4070 SUPER (10DE:2783) Driver version 32.0.15.6590
2024-10-23 20:45:39,439 (GuiMain.py) (Line 2307) [INFO] : Using PySide6
2024-10-23 20:45:39,439 (GuiMain.py) (Line 2308) [INFO] : Qt version: 6.7.3
2024-10-23 20:45:39,439 (GuiMain.py) (Line 2309) [INFO] : PySide6 version: 6.7.3
2024-10-23 20:45:39,501 (shared.py) (Line 491) [INFO] : [1] Thread starter (separator.py) starts
2024-10-23 20:45:39,734 (GuiMain.py) (Line 2314) [DEBUG] : Supported styles: windows11, windowsvista, Windows, Fusion
2024-10-23 20:45:39,735 (GuiMain.py) (Line 2320) [DEBUG] : Current style: windowsvista
2024-10-23 20:45:39,760 (shared.py) (Line 497) [ERROR] : [1] Thread starter (separator.py) failed:
  File "GuiMain.py", line 2312, in <module>
  File "GuiMain.py", line 189, in __init__
Traceback (most recent call last):
  File "shared.py", line 495, in run_and_log
  File "separator.py", line 56, in starter
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\aiden\Desktop\Demucs-GUI_1.3a1_cuda_mkl\torch\lib\backend_with_compiler.dll" or one of its dependencies.

2024-10-23 20:45:39,760 (shared.py) (Line 508) [INFO] : [1] Thread starter (separator.py) ends
```

**Comment by CarlGao4** [comment]
Did you actually extracted **ALL** the contents of the archive file?

**Comment by Sinnaminty** [comment]
Yes, I unzipped the .7z download as normal, but I will redownload and check again once I get home for the day

**Comment by NeuralSamurAI** [comment]
I have this issue as well

**Comment by CarlGao4** [comment]
Please follow the instructions on https://github.com/CarlGao4/Demucs-Gui/blob/debug-win64

**Comment by TNT-333** [comment]
The debugger just crashes and the wmic environment variable fix in the other issue didn't work either, still stuck on Starting

**Comment by CarlGao4** [comment]
The debugger should output a log file in the same path of Demucs-GUI

**Comment by kmadaras** [comment]
Same.

**Comment by CarlGao4** [comment]
> Please follow the instructions on https://github.com/CarlGao4/Demucs-Gui/blob/debug-win64

Does anybody have tried the debugger?

**Comment by TNT-333** [comment]
> > Please follow the instructions on https://github.com/CarlGao4/Demucs-Gui/blob/debug-win64
> 
> Does anybody have tried the debugger?

Yes I did and it didn't work, it just crashed and outputted no file

**Comment by TacticalCrash006** [comment]
Followed instructions with debugger. No file created in .exe location and checked debug folder just in case, still nothing. Having splash screen issue as well.

**Comment by CarlGao4** [comment]
Found missing DLL. Will reupload later.
