### ISSUE TITLE
Bug: Cannot load default model macOS M1 Pro 

### ISSUE THREAD

**Issue by two1zero3** [CarlGao4/Demucs-Gui#92]
### happen

clicking load on the default "htdemucs" model causes an error on 1.3a1

### What is the platform you are using?

macOS

### log

```true
2024-10-30 23:27:49,291 (shared.py) (Line 508) [INFO] : [4] Thread loadModel (GuiMain.py) ends
2024-10-30 23:27:53,064 (shared.py) (Line 491) [INFO] : [5] Thread loadModel (GuiMain.py) starts
2024-10-30 23:27:53,069 (GuiMain.py) (Line 701) [INFO] : Loading model htdemucs from repo /Applications/Demucs-GUI.app/Contents/Frameworks/pretrained
2024-10-30 23:27:53,139 (GuiMain.py) (Line 361) [ERROR] : Failed to load model htdemucs from "/Applications/Demucs-GUI.app/Contents/Frameworks/pretrained":
Traceback (most recent call last):
  File "GuiMain.py", line 357, in loadModel
  File "separator.py", line 266, in __init__
  File "demucs/api.py", line 120, in __init__
  File "demucs/api.py", line 205, in _load_model
  File "demucs/pretrained.py", line 78, in get_model
  File "demucs/repo.py", line 160, in get_model
  File "demucs/repo.py", line 139, in get_model
  File "demucs/repo.py", line 139, in <listcomp>
  File "demucs/repo.py", line 107, in get_model
  File "demucs/states.py", line 59, in load_model
  File "torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "torch/serialization.py", line 1422, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'numpy.core.multiarray'

2024-10-30 23:27:53,184 (shared.py) (Line 508) [INFO] : [5] Thread loadModel (GuiMain.py) ends
```

**Comment by jjeaton** [comment]
I'm also having the same issue

**Comment by CarlGao4** [comment]
Please provide full log

**Comment by CarlGao4** [comment]
The release file has been updated
