### ISSUE TITLE
intel backend is unavailable

### ISSUE THREAD

**Issue by DDXDB** [CarlGao4/Demucs-Gui#93]
### happen

The intel backend cannot be checked after updating the intel GPU 6299 driver

### What is the platform you are using?

Windows

### log

```true
C:\Users\98440\miniconda3\envs\Demucs-Gui\python.exe F:\Demucs-Gui\GUI\GuiMain.py 
2024-11-28 11:44:30,884 (GuiMain.py) (Line 2305) [INFO] : Python version: 3.10.15 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:19) [MSC v.1929 64 bit (AMD64)]
2024-11-28 11:44:30,884 (GuiMain.py) (Line 2306) [INFO] : Demucs GUI version: 1.3b1
2024-11-28 11:44:30,928 (GuiMain.py) (Line 2307) [INFO] : System: Windows-10-10.0.26100-SP0
2024-11-28 11:44:30,928 (GuiMain.py) (Line 2308) [INFO] : Architecture: 64bit
2024-11-28 11:44:30,928 (GuiMain.py) (Line 2309) [INFO] : CPU: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
2024-11-28 11:44:30,928 (GuiMain.py) (Line 2310) [INFO] : CPU count: 12
2024-11-28 11:44:30,937 (GuiMain.py) (Line 2311) [INFO] : System memory: 34266697728 (31.913GB)
2024-11-28 11:44:30,945 (GuiMain.py) (Line 2314) [INFO] : System free memory: 25359933440 (23.616GB)
2024-11-28 11:44:31,656 (GuiMain.py) (Line 2318) [INFO] : System swap memory: 14495514624 (13.5GB)
2024-11-28 11:44:32,356 (find_device_win.py) (Line 344) [INFO] : Found GPU: Intel(R) Arc(TM) A770 Graphics (8086:56A0) Driver version 32.0.101.6299
2024-11-28 11:44:32,356 (find_device_win.py) (Line 344) [INFO] : Found GPU: Intel(R) Arc(TM) A750 Graphics (8086:56A1) Driver version 32.0.101.6299
2024-11-28 11:44:32,358 (GuiMain.py) (Line 2336) [INFO] : Using PySide6
2024-11-28 11:44:32,359 (GuiMain.py) (Line 2337) [INFO] : Qt version: 6.8.0
2024-11-28 11:44:32,359 (GuiMain.py) (Line 2338) [INFO] : PySide6 version: 6.8.0.2
2024-11-28 11:44:32,545 (shared.py) (Line 504) [INFO] : [1] Thread starter (separator.py) starts
2024-11-28 11:44:32,780 (GuiMain.py) (Line 2343) [DEBUG] : Supported styles: windows11, windowsvista, Windows, Fusion
2024-11-28 11:44:32,783 (GuiMain.py) (Line 2349) [DEBUG] : Current style: windowsvista
2024-11-28 11:44:37,879 (separator.py) (Line 70) [ERROR] : Failed to load Intel Extension for PyTorch for the 1 time:
Traceback (most recent call last):
  File "F:\Demucs-Gui\GUI\separator.py", line 63, in starter
    import intel_extension_for_pytorch as ipex  # type: ignore
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 7, in <module>
    import torchvision
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torch\_custom_ops.py", line 253, in inner
    custom_op = _find_custom_op(qualname, also_check_torch_library=True)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torch\_custom_op\impl.py", line 1076, in _find_custom_op
    overload = get_op(qualname)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torch\_custom_op\impl.py", line 1062, in get_op
    error_not_found()
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torch\_custom_op\impl.py", line 1052, in error_not_found
    raise ValueError(
ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.

2024-11-28 11:44:37,885 (separator.py) (Line 70) [ERROR] : Failed to load Intel Extension for PyTorch for the 2 time:
Traceback (most recent call last):
  File "F:\Demucs-Gui\GUI\separator.py", line 63, in starter
    import intel_extension_for_pytorch as ipex  # type: ignore
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 7, in <module>
    import torchvision
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)

2024-11-28 11:44:37,892 (separator.py) (Line 70) [ERROR] : Failed to load Intel Extension for PyTorch for the 3 time:
Traceback (most recent call last):
  File "F:\Demucs-Gui\GUI\separator.py", line 63, in starter
    import intel_extension_for_pytorch as ipex  # type: ignore
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 7, in <module>
    import torchvision
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)

2024-11-28 11:44:37,898 (separator.py) (Line 70) [ERROR] : Failed to load Intel Extension for PyTorch for the 4 time:
Traceback (most recent call last):
  File "F:\Demucs-Gui\GUI\separator.py", line 63, in starter
    import intel_extension_for_pytorch as ipex  # type: ignore
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 7, in <module>
    import torchvision
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)

2024-11-28 11:44:37,905 (separator.py) (Line 70) [ERROR] : Failed to load Intel Extension for PyTorch for the 5 time:
Traceback (most recent call last):
  File "F:\Demucs-Gui\GUI\separator.py", line 63, in starter
    import intel_extension_for_pytorch as ipex  # type: ignore
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\intel_extension_for_pytorch\__init__.py", line 7, in <module>
    import torchvision
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 26, in <module>
    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchvision\_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)

2024-11-28 11:44:37,945 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 6.
2024-11-28 11:44:38,261 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 6 extension.
Traceback (most recent call last):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
2024-11-28 11:44:38,263 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 5.
2024-11-28 11:44:38,265 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 5 extension.
Traceback (most recent call last):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
2024-11-28 11:44:38,265 (utils.py) (Line 93) [DEBUG] : Attempting to load FFmpeg version 4.
2024-11-28 11:44:38,267 (utils.py) (Line 130) [DEBUG] : Failed to load FFmpeg 4 extension.
Traceback (most recent call last):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
2024-11-28 11:44:38,268 (__init__.py) (Line 96) [DEBUG] : Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\__init__.py", line 89, in <module>
    _FFMPEG_EXT = _init_ffmpeg()
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 162, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers, show_error)
  File "C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\torchaudio\_extension\utils.py", line 132, in _find_ffmpeg_extension
    raise ImportError(f"Failed to intialize FFmpeg extension. Tried versions: {ffmpeg_vers}")
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4']
C:\Users\98440\miniconda3\envs\Demucs-Gui\lib\site-packages\demucs\api.py:27: UserWarning: TorchAudio's global backend is now deprecated. Please enable distpatcher by setting `TORCHAUDIO_USE_BACKEND_DISPATCHER=1`, and specify backend when calling load/info/save function.
  import torchaudio as ta
2024-11-28 11:44:38,727 (audio.py) (Line 38) [INFO] : Soundfile version: 0.12.1
2024-11-28 11:44:38,727 (audio.py) (Line 39) [INFO] : libsndfile version: 1.2.0
2024-11-28 11:44:38,727 (audio.py) (Line 40) [INFO] : SoXR version: 0.5.0.post1
2024-11-28 11:44:38,727 (audio.py) (Line 41) [INFO] : libsoxr version: 0.1.3-11-gedbdb40
2024-11-28 11:44:38,728 (separator.py) (Line 89) [INFO] : Demucs version: 4.1.0a3
2024-11-28 11:44:38,728 (separator.py) (Line 90) [INFO] : PyTorch version: 2.1.2+cpu
2024-11-28 11:44:39,813 (audio.py) (Line 79) [INFO] : ffmpeg -version output:
ffmpeg version 7.0.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100

2024-11-28 11:44:39,813 (audio.py) (Line 82) [INFO] : SoXR enabled in FFmpeg
2024-11-28 11:44:39,932 (audio.py) (Line 87) [INFO] : Using ffmpeg from C:\Users\98440\AppData\Local\Microsoft\WinGet\Links\ffmpeg.EXE
2024-11-28 11:44:39,932 (audio.py) (Line 88) [INFO] : ffprobe -version output:
ffprobe version 7.0.1-full_build-www.gyan.dev Copyright (c) 2007-2024 the FFmpeg developers
built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100

2024-11-28 11:44:40,060 (audio.py) (Line 109) [INFO] : FFmpeg protocols: async, bluray, cache, concat, concatf, crypto, data, fd, ffrtmpcrypt, ffrtmphttp, file, ftp, gopher, gophers, hls, http, httpproxy, https, ipfs, ipns, mmsh, mmst, pipe, rist, rtmp, rtmpe, rtmps, rtmpt, rtmpte, rtmpts, rtp, sftp, srt, srtp, subfile, tcp, tls, udp, udplite, zmq
2024-11-28 11:44:41,072 (shared.py) (Line 521) [INFO] : [1] Thread starter (separator.py) ends
2024-11-28 11:44:41,418 (shared.py) (Line 504) [INFO] : [2] Thread checkUpdate (shared.py) starts
2024-11-28 11:44:41,424 (shared.py) (Line 537) [INFO] : Checking for updates...
2024-11-28 11:44:42,657 (shared.py) (Line 540) [INFO] : Latest version: 1.3b1
2024-11-28 11:44:42,657 (shared.py) (Line 521) [INFO] : [2] Thread checkUpdate (shared.py) ends
c
```

**Comment by CarlGao4** [comment]
How did you install intel_extension_for_pytorch?
You can use the release binaries if you don't need to modify the source code

**Comment by DDXDB** [comment]
> How did you install intel_extension_for_pytorch? You can use the release binaries if you don't need to modify the source code

I installed IPEX according to intel's guidelines, and the environment was fine until the driver update

**Comment by CarlGao4** [comment]
Can you try reinstalling Intel's modified torch, torchaudio, torchvision? IPEX requires the modified version.

**Comment by CarlGao4** [comment]
I think I've found the error. IPEX requires its modified PyTorch and torchaudio and torchvision. You PyTorch version is `2.1.2+cpu`, but it's modified version should be `2.1.0a0` as I remember.

**Comment by DDXDB** [comment]
> I think I've found the error. IPEX requires its modified PyTorch and torchaudio and torchvision. You PyTorch version is `2.1.2+cpu`, but it's modified version should be `2.1.0a0` as I remember.
> 
> Please try uninstalling torch, torchaudio and torchvision first, and install them following the IPEX installation instructions

I tried to install IPEX v2.3.110+xpu, although there was a PIP error

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
demucs 4.1.0a3 requires torchaudio<2.2,>=0.8, but you have torchaudio 2.3.1.post0+cxx11.abi which is incompatible.
```

IPEX installation instructions

```
conda install libuv
python -m pip install torch==2.3.1.post0+cxx11.abi torchvision==0.18.1.post0+cxx11.abi torchaudio==2.3.1.post0+cxx11.abi intel-extension-for-pytorch==2.3.110.post0+xpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
```


But the program worked fine

**Comment by DDXDB** [comment]
The compatibility with IPEX v2.5.10+xpu is confirmed, but the pip error still exists during installation, but the actual work is not affected.

In addition, starting with v2.3.110+xpu, Intel does not need to install Intel® oneAPI Base Toolkit.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
demucs 4.1.0a3 requires torchaudio<2.2,>=0.8, but you have torchaudio 2.5.1+cxx11.abi which is incompatible.
```
